// These are used in case API call to retrieve posts fails. Should be updated to recent posts occasionally

import type { PostType } from '../../beehiiv/types/post'

export const fallback: PostType[] = [
  {
    id: 'post_c6d044fa-ebf8-439d-adbe-d55488283e81',
    title: 'China continues to lead (part II)',
    subtitle: 'Did DeepSeek “deep six” the AI energy demand story?',
    authors: ['Nick van Osdol'],
    created: 1738214123,
    status: 'confirmed',
    publish_date: 1738278000,
    displayed_date: null,
    split_tested: false,
    subject_line: '🐧 China continues to lead (part II)',
    preview_text: 'Did DeepSeek “deep six” the AI energy demand story?',
    slug: 'china-continues-to-lead-part-ii',
    thumbnail_url:
      'https://beehiiv-images-production.s3.amazonaws.com/uploads/asset/file/2aea54c8-af8e-49d4-adbf-481ce70c5386/shutterstock_2577645509.jpg?t=1738214833',
    web_url: 'https://www.keepcool.co/p/china-continues-to-lead-part-ii',
    audience: 'both',
    platform: 'both',
    content_tags: ['featured', 'newsletter'],
    meta_default_description:
      'In one fell swoop, a two-month-old Chinese startup may have rendered moot a year’s worth of hand-wringing about energy demand growth for AI. Or it didn’t. Doesn’t matter. What matters is we need clean electrons no matter what.',
    meta_default_title: 'China continues to lead (part II)',
    hidden_from_feed: false,
  },
  {
    id: 'post_fa0bb805-e133-4b3a-b3a9-2d9facd55d79',
    title: 'Scorched earth policy',
    subtitle: 'And how to navigate it',
    authors: ['Nick van Osdol'],
    created: 1737673469,
    status: 'confirmed',
    publish_date: 1737678600,
    displayed_date: null,
    split_tested: false,
    subject_line: '🐧 Scorched earth policy',
    preview_text: 'And how to navigate it',
    slug: 'scorched-earth-policy',
    thumbnail_url:
      'https://beehiiv-images-production.s3.amazonaws.com/uploads/asset/file/eb08d8f8-3e19-43bd-8138-f17862a056d9/trump.png?t=1737675543',
    web_url: 'https://www.keepcool.co/p/scorched-earth-policy',
    audience: 'both',
    platform: 'both',
    content_tags: ['featured'],
    meta_default_description:
      'It’s been a rough week if you’re a closer watcher of climate policy in the U.S. or from afar. There’s far too much news to parse. Which is exactly Trump’s strategy. This newsletter explains what I mean by that, what it means for you, and offers suggestions to stay afloat.',
    meta_default_title: 'Scorched earth policy',
    hidden_from_feed: false,
  },
  {
    id: 'post_517d49b3-0ee4-4da2-bb07-b09e33566c57',
    title: 'The world-ending fire',
    subtitle: 'And why it’s not exclusively a climate change ‘story’',
    authors: ['Nick van Osdol'],
    created: 1737072391,
    status: 'confirmed',
    publish_date: 1737079200,
    displayed_date: null,
    split_tested: false,
    subject_line: '🐧 The world-ending fire',
    preview_text: 'And why it’s not exclusively a climate change ‘story’',
    slug: 'the-world-ending-fire',
    thumbnail_url:
      'https://beehiiv-images-production.s3.amazonaws.com/uploads/asset/file/8322d838-d7b1-4a8a-9823-39a57b7d88af/IMG_5507.JPG?t=1737074069',
    web_url: 'https://www.keepcool.co/p/the-world-ending-fire',
    audience: 'both',
    platform: 'both',
    content_tags: ['featured'],
    meta_default_description:
      'The LA fires may end up causing more damage than all other global natural disasters across all of 2024 did. Still, they’re not simply a climate change story. Yes, climate change is part of the story. But really, the call to attention is to appreciate the unsustainability of many if not most of our modern societal systems.',
    meta_default_title: '',
    hidden_from_feed: false,
  },
  {
    id: 'post_5c57ac99-7251-44bf-b588-c45808b46046',
    title: 'Greener steel exists',
    subtitle: 'And it’s made in the U.S.A.',
    authors: ['Nick van Osdol'],
    created: 1722871199,
    status: 'confirmed',
    publish_date: 1723154400,
    displayed_date: null,
    split_tested: false,
    subject_line: '🐧 Greener steel exits',
    preview_text: 'And it’s made in the U.S.A.',
    slug: 'greener-steel-exists',
    thumbnail_url:
      'https://beehiiv-images-production.s3.amazonaws.com/uploads/asset/file/baa973c0-48a3-4a16-adb4-82ad1658294a/Interior_012.jpg?t=1722872301',
    web_url: 'https://www.keepcool.co/p/greener-steel-exists',
    audience: 'both',
    platform: 'both',
    content_tags: ['featured'],
    meta_default_description:
      'Heavy industrial sectors like steelmaking are often dubbed ‘hard to abate.’ Nucor already makes steel with significantly fewer emissions.',
    meta_default_title: 'Greener steel exists',
    hidden_from_feed: false,
  },
  {
    id: 'post_2fad4aaa-5fde-4456-b80e-d8094920d2a6',
    title: 'NGL, LNG is complicated',
    subtitle: "Why Biden's LNG call is a case study in climate complexity",
    authors: ['Nick van Osdol'],
    created: 1706573587,
    status: 'confirmed',
    publish_date: 1706827500,
    displayed_date: null,
    split_tested: false,
    subject_line: 'NGL, LNG is complicated',
    preview_text: "Why Biden's LNG call is a case study in climate complexity",
    slug: 'not-gonna-lie-lng-is-complicated',
    thumbnail_url:
      'https://beehiiv-images-production.s3.amazonaws.com/uploads/asset/file/9ae61827-9583-451d-ae4b-0836ed429f33/shutterstock_2315527493.jpg?t=1706375406',
    web_url: 'https://www.keepcool.co/p/not-gonna-lie-lng-is-complicated',
    audience: 'both',
    platform: 'both',
    content_tags: ['featured'],
    meta_default_description:
      "Why Biden's decision to halt new approvals for LNG infrastructure is a case study in the complexity of the energy transition.",
    meta_default_title: 'NGL, LNG is complicated',
    hidden_from_feed: false,
  },
  {
    id: 'post_0c703db8-339b-4bf2-bf1a-3324f2b57e28',
    title: 'Blaming the wind',
    subtitle: "Decomposing what's happening in wind energy",
    authors: ['Nick van Osdol'],
    created: 1700421911,
    status: 'confirmed',
    publish_date: 1700422534,
    displayed_date: 1696521600,
    split_tested: false,
    subject_line: '',
    preview_text: '',
    slug: 'blaming-the-wind',
    thumbnail_url:
      'https://beehiiv-images-production.s3.amazonaws.com/uploads/asset/file/196c93e2-421c-42f3-87e7-dd4d428d1bf8/image.png?t=1700422051',
    web_url: 'https://www.keepcool.co/p/blaming-the-wind',
    audience: 'free',
    platform: 'web',
    content_tags: ['featured'],
    meta_default_description:
      "Decomposing what's happening in the wind energy industry in 2023.",
    meta_default_title: 'Blaming the wind',
    hidden_from_feed: false,
  },
]
