// These are used in case API call to retrieve posts fails. Should be updated to recent posts occasionally

export const fallback = [
  {
    id: 'post_dfa9125a-bfb2-4422-9657-ebbec9fa0eae',
    title: 'The When, Where, Who, and Why of Methane Emissions',
    subtitle: 'Minimal U.S. political discussion! Lots of pretty pictures!!',
    authors: ['Nick van Osdol', 'Lauren Singer'],
    created: 1739428223,
    status: 'confirmed',
    publish_date: 1739482331,
    displayed_date: null,
    split_tested: false,
    subject_line: '🐧 The When, Where, Who, and Why of Methane Emissions',
    preview_text: 'Turning Data into Action with Visualizing Energy',
    slug: 'the-when-where-who-and-why-of-methane-emissions',
    thumbnail_url:
      'https://beehiiv-images-production.s3.amazonaws.com/uploads/asset/file/3fb21612-afdf-4230-86b0-6b052f17d265/image.png?t=1739435743',
    web_url:
      'https://www.keepcool.co/p/the-when-where-who-and-why-of-methane-emissions',
    audience: 'both',
    platform: 'both',
    content_tags: ['article'],
    meta_default_description:
      "Methane emissions mitigation would be one of the fastest ways to slow global warming. Solutions exist and are often economically viable, not just environmental nice-to-haves. Still, methane receives a tiny sliver of total climate finance. Hence, it's worth asking (and iteratively testing) how better, data-driven storytelling might shift this dynamic.",
    meta_default_title: null,
    hidden_from_feed: false,
  },
  {
    id: 'post_9a0b9df7-ae74-482f-9bc3-c33afe1cb77e',
    title: "A lot's gonna change",
    subtitle: 'Plus lots more across climate tech and energy',
    authors: ['Nick van Osdol'],
    created: 1739187182,
    status: 'confirmed',
    publish_date: 1739188589,
    displayed_date: null,
    split_tested: false,
    subject_line: "🐧 A lot's gonna change",
    preview_text: 'Plus lots more across climate tech and energy',
    slug: 'a-lot-s-gonna-change',
    thumbnail_url:
      'https://beehiiv-images-production.s3.amazonaws.com/uploads/asset/file/c7de7c4e-2abb-4de7-99c1-d09cf4cdb25f/hassan-pasha-7SjEuEF06Zw-unsplash.jpg?t=1739188554',
    web_url: 'https://www.keepcool.co/p/a-lot-s-gonna-change',
    audience: 'both',
    platform: 'both',
    content_tags: ['newsletter'],
    meta_default_description: null,
    meta_default_title: null,
    hidden_from_feed: false,
  },
  {
    id: 'post_59e139a0-4589-42e2-adf5-374658872cd0',
    title: 'Subsidy situationship',
    subtitle: 'Uncertainty remains the only certainty in the U.S.',
    authors: ['Nick van Osdol'],
    created: 1738906625,
    status: 'confirmed',
    publish_date: 1738926000,
    displayed_date: null,
    split_tested: false,
    subject_line: '🐧 Subsidy situationship',
    preview_text: 'Uncertainty remains the only certainty in the U.S.',
    slug: 'subsidy-situationship',
    thumbnail_url:
      'https://beehiiv-images-production.s3.amazonaws.com/uploads/asset/file/f83ebe04-bbac-4857-b9cd-cb6a4a11f0cc/shutterstock_2502188579.jpg?t=1738913211',
    web_url: 'https://www.keepcool.co/p/subsidy-situationship',
    audience: 'both',
    platform: 'both',
    content_tags: ['article'],
    meta_default_description: null,
    meta_default_title: null,
    hidden_from_feed: false,
  },
]
